- name: Setting redis into Consul
  hosts: localhost
  vars:
    data:
      ## Persistence
      - source: "{{ playbook_dir }}/files/s3/static-assets.json"
        key: services/s3/static-assets
  tasks:
    - name: Update configs into Consul
      consul_kv:
        value: "{{ lookup('file','{{ item.source }}') | from_json | to_nice_json(indent=2) }}"
        key: "{{ item.key }}"
        host: "127.0.0.1"
        # host: "{{ groups['consul-master'][0] }}"
        state: present
      with_items:
        - "{{data}}"
