consul_data_path: "/mnt/{{ group_names | select('match', '^module_consul_server_node_[0-9]+$') | first | regex_replace('\\.', '_') | regex_replace('([0-9]+)$','consul_\\1') }}"
consul_node_role: server
consul_bootstrap_expect: true
