nomad_stateful_agent_id: "{{ group_names | select('match', '^module_nomad_stateful_agent_node_[0-9]+$') | first | regex_replace('^module_nomad_stateful_agent_node_([0-9]+)$','\\1') }}"
nomad_meta:
  persistence_volume: Yes