nomad_node_role: server
nomad_bind_address: "{{ansible_eth1.ipv4.address}}"
nomad_data_dir: "/mnt/{{ group_names | select('match', '^module_nomad_server_node_[0-9]+$') | first | regex_replace('\\.', '_') | regex_replace('([0-9]+)','nomad_\\1') }}"
