kafka_node_id: "{{ group_names | select('match', '^module_kafka_cluster_node_[0-9]+$') | first | regex_replace('^module_kafka_cluster_node_([0-9]+)$','\\1') | int + 1}}"
kafka_broker:
  broker_id: "{{ kafka_node_id }}"
  datadir: 
    - "/mnt/kafka_{{ group_names | select('match', '^module_kafka_cluster_node_[0-9]+$') | first | regex_replace('^module_kafka_cluster_node_([0-9]+)$','\\1') }}/data"
  properties:
    # Default number of partition
    num.partitions: 4
    default.replication.factor: 2
jmxexporter_enabled: true
kafka_broker_service_environment_overrides:
  KAFKA_HEAP_OPTS: "-Xmx2g"
zookeeper_path: "/kafka"